//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServiceStackClientMD {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Repeater rptrTests;
		
		protected System.Web.UI.WebControls.Label hUsername;
		
		protected System.Web.UI.WebControls.Label lMessage;
		
		protected System.Web.UI.WebControls.Label lSuccess;
		
		protected System.Web.UI.WebControls.Label lUser;
		
		protected System.Web.UI.WebControls.Label lUsername;
		
		protected System.Web.UI.WebControls.Label lFirstName;
		
		protected System.Web.UI.WebControls.Label lLastName;
		
		protected System.Web.UI.WebControls.Label lAddress;
		
		protected System.Web.UI.WebControls.PlaceHolder phAddress;
		
		protected System.Web.UI.WebControls.Label lAddressStreet;
		
		protected System.Web.UI.WebControls.Label lCity;
		
		protected System.Web.UI.WebControls.Label lState;
		
		protected System.Web.UI.WebControls.Label lZip;
	}
}
