//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.UI;
using ServiceStack.ServiceClient.Web;
using TestServiceDTOs.Responses;
using TestServiceDTOs.Requests;
using TestServiceDTOs;
using System.Web.UI.WebControls;

namespace TestServiceStackClientMD
{
	public partial class Default : System.Web.UI.Page
	{
		public void Page_Load(object sender, EventArgs e)
		{
			AuthenticateRequest[] tests = new [] {
				new AuthenticateRequest()
                {
                    Username = "user1",
                    Password = "password"
                },
				new AuthenticateRequest()
                {
                    Username = "user2",
                    Password = "password"
                },
				new AuthenticateRequest()
                {
                    Username = "user3",
                    Password = "password"
                }
			};
			
			
			rptrTests.DataSource = tests;
			rptrTests.ItemDataBound += RptrTestsItemDataBound;
			rptrTests.DataBind();
		}

		void RptrTestsItemDataBound (object sender, System.Web.UI.WebControls.RepeaterItemEventArgs e)
		{
			var request = (AuthenticateRequest)e.Item.DataItem;
			var lMessage = (Label)e.Item.FindControl("lMessage");
			var lSuccess = (Label)e.Item.FindControl("lSuccess");
			var lUser = (Label)e.Item.FindControl("lUser");
			var lUsername = (Label)e.Item.FindControl("lUsername");
			var lFirstName = (Label)e.Item.FindControl("lFirstName");
			var lLastName = (Label)e.Item.FindControl("lLastName");
			var lAddress = (Label)e.Item.FindControl("lAddress");
			var lAddressStreet = (Label)e.Item.FindControl("lAddressStreet");
			var lCity = (Label)e.Item.FindControl("lCity");
			var lState = (Label)e.Item.FindControl("lState");
			var lZip = (Label)e.Item.FindControl("lZip");
			var phAddress = (PlaceHolder)e.Item.FindControl("phAddress");
			var hUsername = (Label)e.Item.FindControl("hUsername");
			
			hUsername.Text = request.Username;
			
			//var restClient = new JsonServiceClient("http://localhost:25000/");
			var restClient = new XmlServiceClient("http://localhost:25000/");
			restClient.Timeout = new TimeSpan(0, 0, 30);
            var response = restClient.Send<AuthenticateResponse>(request);
			
			lMessage.Text = response.Message ?? "null";
			lSuccess.Text = response.Success ? "true" : "false";
			
			if(response.User == null)
			{
				lUser.Text = "null";
			} else {
				lUser.Text = "not null";
				User u = response.User;
				lUsername.Text = u.Username ?? "null";
				lFirstName.Text = u.FirstName ?? "null";
				lLastName.Text = u.LastName ?? "null";
				if(u.Address == null)
				{
					lAddress.Text = "null";
					phAddress.Visible = false;
				} else {
					lAddress.Text = "not null";
					
					Address a = u.Address;
					lAddressStreet.Text = a.Street ?? "null";
					lCity.Text = a.City ?? "null";
					lState.Text = a.State ?? "null";
					lZip.Text = a.Zip ?? "null";
				}
			}
		}
	}
}

